apiVersion: v1
kind: Secret
metadata:
  name: passwords
  namespace: kt2l
data:
  # 2UKowq7JszoxAzfSvcCKRTpD4Cb
  admin_password: MlVLb3dxN0pzem94QXpmU3ZjQ0tSVHBENENiCg==
  # ov7yV9EzZRMp65ZHaurPRYy2PwD
  user_password: b3Y3eVY5RXpaUk1wNjVaSGF1clBSWXkyUHdECg==
  # tvanR3WHokmAexboBeaqGm6LVub
  viewer_password: dHZhblIzV0hva21BZXhib0JlYXFHbTZMVnViCg==
