apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lorem
  name: lorem
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lorem
  template:
    metadata:
      labels:
        app: lorem
    spec:
      containers:
        - image: mhus/example-lorem:latest
          imagePullPolicy: Always
          name: test-server
          env:
            - name: REPEAT
              value: '60'
            - name: SLEEP
              value: '1'
            - name: TERMINATE_SLEEP
              value: '20'