apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kt2l-chart.serviceAccountName" . }}
  labels:
    {{- include "kt2l-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "metrics.k8s.io","apps","batch","extensions","networking.k8s.io","storage.k8s.io","rbac.authorization.k8s.io","autoscaling","policy", "events.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
