#
# kt2l - KT2L (ktool) is a web based tool to manage your kubernetes clusters.
# Copyright © 2024 Mike Hummel (mh@mhus.de)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#


- hosts: demo-hosts

  post_tasks:
    - name: Stop Minikube
      command: minikube stop
      environment:
        KUBECONFIG: /home/user/.kube/config-minikube
      become: yes
      become_user: user
    - name: Start Minikube
      command: minikube start
      environment:
        KUBECONFIG: /home/user/.kube/config-minikube
      become: yes
      become_user: user
    - name: Prepare kube config
      command: /root/prepare-kube-config.sh
      become: yes
      become_user: root
