
login:
  users:
  passwords:
  localAuthEnabled: false
  oauth2Enabled: true
  oauth2Providers:
    - id: google
      roleMapping:
        role: [READ]
  oauth2Accept:
    - pattern: '.*@company.com'
      provider: google
      defaultRoles: [READ]

environment:
  GOOGLE_CLIENT_ID: "1234567890.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "1234567890"

role:
  rules:
    - apiGroups: ["", "metrics.k8s.io","apps","batch","extensions","networking.k8s.io","storage.k8s.io","rbac.authorization.k8s.io","autoscaling","policy", "events.k8s.io"]
      resources: ["*"]
      verbs: ["read", "list","watch"]

image:
  tag: "snapshot-20240704232901"
  pullPolicy: Never
