ollamaUrl: http://localhost:11434
questions:
  language: |
    Translate the following text to ${language}:
    
    ${content}
  resource: |
    Do you see problems in the following kubernetes resource?
    
    ${content}