defaultCluster: arn:aws:eks:eu-central-1:449305603284:cluster/q_machine_priv_dev
defaultResourceType: "pods"
defaultNamespace: default
clusters:
  - name: colima
    title: "Colima"
    enabled: true
    color: green