#
# kt2l-test - kt2l integration tests
# Copyright © 2024 Mike Hummel (mh@mhus.de)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

windowWidth: 400px
enabled: true
sticky: false
contexts:
  default:
    - name: Documentation
      action: docs
      document: usage/cluster
    - name: Chat Agent
      action: ai
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  details:
    - name: Chat Agent
      action: ai
      prompt: Answer with a new resources example. [resource] {{content}}
    - name: Details
      action: docs
      document: usage/details
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  resources:
    - name: Resources
      action: docs
      document: usage/resources
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  logs:
    - name: Logs
      action: docs
      document: usage/logs
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  shell:
    - name: Shell
      action: docs
      document: usage/shell
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  ai:
    - name: AI
      action: docs
      document: usage/ai
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  exec:
    - name: Exec
      action: docs
      document: usage/exec
      default: true
    - name: Snippets
      action: snippets
      repo: https://github.com/mhus/kt2l-snippets.git
      type: bash
      path: exec
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  create:
    - name: Create
      action: docs
      document: usage/create
    - name: Snippets
      action: snippets
      repo: https://github.com/mhus/kt2l-snippets.git
      type: yaml
      path: create
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  events:
    - name: Events
      action: docs
      document: usage/events
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  global_cfg:
    - name: Global Settings
      action: docs
      document: usage/global_cfg
      default: true
  user_cfg:
    - name: User Settings
      action: docs
      document: usage/user_cfg
      default: true
  portforward:
    - name: Port Forward
      action: docs
      document: usage/portforward
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  edit_secret:
    - name: Edit Secret
      action: docs
      document: usage/edit_secret
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  edit_configmap:
    - name: Edit ConfigMap
      action: docs
      document: usage/edit_configmap
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  vis:
    - name: Visualize
      action: docs
      document: vis
      default: true
  storage:
    - name: Storage
      action: docs
      document: usage/storage
      default: true
    - name: Kubernetes
      action: link
      href: https://kubernetes.io/docs/home/
  localbash:
    - name: Local Bash
      action: docs
      document: localbash
      default: true
  system_info:
    - name: System Info
      action: docs
      document: usage/system_info
      default: true