users:
  - name: "admin"
    password: "{generate}"
    roles:
      - "READ"
      - "WRITE"
      - "LOCAL"
      - "SETTINGS"
      - "ADMIN"
  - name: "user"
    password: "{generate}"
    roles:
    - "READ"
    - "WRITE"
    - "SETTINGS"
  - name: "viewer"
    password: "{noop}viewer"
    roles:
      - "READ"
  - name: "dummy"
    password: "{noop}dummy"
    roles:
  - name: "autologin"
    password: "{generate}"
    roles:
    - "READ"
    - "WRITE"
    - "LOCAL"
    - "SETTINGS"
    - "ADMIN"