#
# kt2l-core - kt2l core implementation
# Copyright © 2024 Mike Hummel (mh@mhus.de)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

log:
  maxCachedEntries: 1000
  maxCachedCharacters: 30000
  jsonFields: "@timestamp,severity,message"
core:
  idle:
    enabled: true
    autoExtend: true
    autoExtendWaitSeconds: 1
    notifyBeforeSeconds: 90
    maxInactiveIntervalSeconds: 0
  uiLostEnabled: false
  uiTimeoutSeconds: 60
  trackBrowserMemoryUsage: false
snippets:
  maxVisibleResults: 30
portForward:
  firstPort: 9000
resourcesGrid:
  colors: true
  showResourceVersion: false
  historyMaxSize: 50
localBash:
  path: /bin/bash
  argument: -i
clusterOverview:
  colors: true
vis:
  presets:
    - name: Apps
      types:
        - pod
        - deployment
        - statefulset
        - daemonset
        - replicaset
        - job
        - cronjob
        - service
        - namespace
        - ingress
    - name: Config
      types:
        - pod
        - configmap
        - secret
    - name: Volumes
      types:
        - persistentvolume
        - persistentvolumeclaim
        - storageclass
        - pod
        - namespace
    - name: Network
      types:
        - service
        - ingress
        - networkpolicy
        - pod
        - namespace
    - name: Nodes
      namespace: '[all]'
      types:
        - node
        - pod
    - name: All
      regex: '.*'
    - name: None
      types:
