{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kt2l-chart.serviceAccountName" . }}
  labels:
    {{- include "kt2l-chart.labels" . | nindent 4 }}
rules:
  {{ .Values.role.rules | toYaml | nindent 2 }}
{{- end }}