apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kt2l-chart.fullname" . }}-passwords
  namespace: {{ .Values.namespace.name }}
data:
  {{- range $key, $val := .Values.login.passwords }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
