
- hosts: demo-hosts
  pre_tasks:
    - name: add user
      user:
        name: "user"
        uid: 1001
        shell: /bin/bash
    - name: Create File
      copy:
        content: |
          user ALL=(ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/10-install-user
        owner: root
        group: root
        mode: 0440

  roles:
    - docker_host
    - minikube_host

  post_tasks:
    - name: Add user to docker group
      user:
        name: user
        groups: docker
        append: yes
    - name: Restart docker service
      service:
        name: docker
        state: restarted
    - name: Start Minikube
      command: minikube start
      become: yes
      become_user: user
    - name: copy config files
      copy:
          src: config/
          dest: /home/user/config/local/
          owner: user
          group: user
          mode: 0755
    - name: Start Ollama docker container
      community.docker.docker_container:
        name: ollama
        image: ollama/ollama
        ports:
            - "11434:11434"
        volumes:
          - ollama:/root/.ollama
    - name: Install Ollama model
      community.docker.docker_container_exec:
        container: ollama
        command: ollama pull llama3
    - name: Start KT2L docker container
      community.docker.docker_container:
        name: kt2l-server
        image: mhus/kt2l-server:snapshot
        network_mode: host
        env:
          CONFIGURATION_DIRECTORY: /home/user/config
        volumes:
          - "/home/user:/home/user"