#
# kt2l - KT2L (ktool) is a web based tool to manage your kubernetes clusters.
# Copyright © 2024 Mike Hummel (mh@mhus.de)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#


- hosts: demo-hosts
  pre_tasks:
    - name: add user
      user:
        name: "user"
        uid: 1001
        shell: /bin/bash
    - name: Create File
      copy:
        content: |
          user ALL=(ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/10-install-user
        owner: root
        group: root
        mode: 0440
    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.31.3/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 0755

  roles:
    - docker_host
    - minikube_host

  post_tasks:
    - name: Add user to docker group
      user:
        name: user
        groups: docker
        append: yes
    - name: Restart docker service
      service:
        name: docker
        state: restarted
    - name: Start Minikube
      command: minikube start
      become: yes
      become_user: user
    - name: copy config files
      copy:
          src: config/
          dest: /home/user/config/local/
          owner: user
          group: user
          mode: 0755
    - name: Start Ollama docker container
      community.docker.docker_container:
        name: ollama
        image: ollama/ollama
        ports:
            - "11434:11434"
        volumes:
          - ollama:/root/.ollama
    - name: Install Ollama model
      community.docker.docker_container_exec:
        container: ollama
        command: ollama pull llama3
    - name: Start KT2L docker container
      community.docker.docker_container:
        name: kt2l-server
        image: mhus/kt2l-server:snapshot
        network_mode: host
        env:
          CONFIGURATION_DIRECTORY: /home/user/config
        volumes:
          - "/home/user:/home/user"