#
# kt2l - KT2L (ktool) is a web based tool to manage your kubernetes clusters.
# Copyright © 2024 Mike Hummel (mh@mhus.de)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

---

- name: APT Update
  apt:
    update_cache: yes
- name: Install CA certificates
  apt:
    name:
      - ca-certificates
    state: present
- name: install keyrings
  command: install -m 0755 -d /etc/apt/keyrings
- name: Get Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
- name: Change permissions of Docker GPG key
  command: chmod a+r /etc/apt/keyrings/docker.asc
- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: /etc/apt/sources.list.d/docker.list
- name: apt update
  apt:
    update_cache: yes
- name: Install docker with apt
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
- name: Add user to docker group
  user:
    name: user
    groups: docker
    append: yes
- name: Restart docker service
  service:
    name: docker
    state: restarted
