name: Build and Publish Docs to GitHub Pages

on:
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

#      - name: Generate Javadoc
#        run: mvn javadoc:aggregate -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: cd docs && npm ci
      - run: cd docs && npm run build
#      - run: cp -R target/site/apidocs docs/build/

      - name: Setup gh-pages
        run: git clone https://github.com/mhus/kt2l.git -b gh-pages gh-pages
      - name: Copy content
        run: cd gh-pages/docs; rm -rf docs;cp ../../docs/build docs
      - name: prepare git config
        run: |
          cd gh-pages
          pwd
          echo "[gc]" >> .git/config
          echo "	auto = 0" >> .git/config
          echo "[http \"https://github.com/\"]" >> .git/config
          cat ../.git/config|grep "extraheader" >> .git/config
      - name: commit
        run: |
          set -x
          cd gh-pages
          git add docs/docs
          git config --global user.name 'Robot'
          git config --global user.email 'mhus@users.noreply.github.com'
          git commit -m "Update docs"
          git push