
#
# This file is part of kt2l.
#
# kt2l is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# kt2l is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kt2l.  If not, see <http://www.gnu.org/licenses/>.
#

name: Build

on:
  workflow_dispatch:
  push:
#    branches:
#      - main
#    paths-ignore:
#      - '*.md'
#      - 'docs/**'
#      - 'config/**'
#      - 'misc/**'
    pull_request:
      branches:
        - main
      paths-ignore:
        - '*.md'
        - 'docs/**'
        - 'config/**'
        - 'misc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up WebKit GTK
        run: |
          sudo apt-get update
          sudo sudo apt-get install -y libwebkit2gtk-4.1
      - name: mhus-commons
        run: |
          if [ $(cat pom.xml|grep mhus-common.version|grep -c SNAPSHOT) -eq 1 ]; then
            echo "Build mhus-commons"
            echo "================"
            git clone https://github.com/mhus/mhus-commons.git
            cd mhus-commons
            mvn install -B -U || exit 1
            cd ..
            rm -rf mhus-commons
          fi
#      - name: vis-network-vaadin
#        run: |
#          echo "Build vis-network-vaadin"
#          echo "================"
#          git clone https://github.com/mhus/vis-network-vaadin.git
#          cd vis-network-vaadin
#          mvn install -B -Pproduction || exit 1
#          cd ..
#          rm -rf vis-network-vaadin
#      - name: vaadin-raw-xterm-addon
#        run: |
#          echo "Build vaadin-raw-xterm-addon"
#          echo "================"
#          git clone https://github.com/mhus/vaadin-raw-xterm-addon.git
#          cd vaadin-raw-xterm-addon
#          mvn install -B -Pproduction || exit 1
#          cd ..
#          rm -rf vaadin-raw-xterm-addon
#      - name: Purge snapshots
#        run: |
#          mvn dependency:purge-local-repository -B -Dinclude:de.mhus.lib:mhus-commons,de.mhus.kt2l:vis-network-vaadin,de.mhus.kt2l:vaadin-raw-xterm-addon
      - name: Prepare
        run: ./launcher/prepare.sh
      - name: Compile
        run: |
          mvn -pl kt2l-core,kt2l-desktop -am -B clean package -Plinux-amd64 -Pproduction -Pintegration_tests -Dspring.profiles.active=prod -Dvaadin.force.production.build=true
      - name: Integration Tests
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          mvn -pl kt2l-test -am -B verify -Plinux-amd64 -Pproduction -Pintegration_tests -Dspring.profiles.active=prod -Dvaadin.force.production.build=true
        env:
          TEST_DEBUG: false
          TEST_SCREENSHOTS: false
