name: Deploy Website CI

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages
  workflow_run:
    workflows: ["Release snapshot", "Release snapshot mac"]
    types:
      - completed
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: deploy_page
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.2'
      - run: cd kt2l.org;npm ci
      - run: cd kt2l.org;npm run build
#      - run: npm test
      - run: rm -rf docs/static
      - run: cp -r kt2l.org/build/* docs/
      - name: commit snapshot
        if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
        run: |
          git add .
          git config --global user.name 'Robot'
          git config --global user.email 'mhus@users.noreply.github.com'
          git commit -am "Webpage"
          git push