#
# This file is part of kt2l.
#
# kt2l is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# kt2l is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kt2l.  If not, see <http://www.gnu.org/licenses/>.
#

name: Release snapshot mac

on:
  workflow_dispatch:

jobs:

  release:
    runs-on: macos-14-arm64
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: download server binaries
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
              echo "Fatal: AWS_ACCESS_KEY_ID not correct set"
              exit 1
          fi
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
              echo "Fatal: AWS_SECRET_ACCESS_KEY not correct set"
              exit 1
          fi
          mkdir -p kt2l-server/target
          cd kt2l-server/target

          ENTRIES=$(aws s3 ls kt2l-downloads/snapshots/|sed "s/  / /g"|cut -d ' ' -f 4|grep -e ^kt2l-server)
          echo Found $ENTRIES
          FILENAME=$ENTRIES
          for e in "$ENTRIES"; do
            FILENAME=$e
          done
          echo "Download $FILENAME"
          aws s3 cp s3://kt2l-downloads/snapshots/$FILENAME kt2l-server.zip || exit 1
          unzip kt2l-server.zip || exit 1
          cp kt2l-server/kt2l-server-0.0.1-SNAPSHOT.jar . || exit 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: create Mac desktop bundle
        run: ./kt2l-desktop/launcher/create-mac.sh
