
#
# This file is part of kt2l.
#
# kt2l is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# kt2l is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kt2l.  If not, see <http://www.gnu.org/licenses/>.
#

name: Release

on:
  workflow_dispatch:
    inputs:
      create_documentation:
        description: 'Create documentation'
        required: true
        default: true
        type: boolean
      create_server_zip:
        description: 'Create Server ZIP'
        required: true
        default: true
        type: boolean
      create_container:
        description: 'Create Server Docker Container'
        required: true
        default: true
        type: boolean
      create_macosx_aarch64:
        description: 'Create Max OSX AARCH64 Bundle'
        required: true
        default: true
        type: boolean
      create_windows_amd64:
        description: 'Create Windows AMD64 Bundle'
        required: true
        default: true
        type: boolean
      create_deb_amd64:
        description: 'Create Linux deb AMD64 Package'
        required: true
        default: true
        type: boolean
      create_all_others:
        description: 'Create Other Platform Desktop Jars'
        required: true
        default: false
        type: boolean
      integration_tests:
        description: 'Run integration tests'
        required: true
        default: true
        type: boolean
      update_website:
        description: 'Trigger update website as final step'
        required: true
        default: true
        type: boolean
      sonarcloud:
        description: 'Push analysis to SonarCloud'
        required: true
        default: true
        type: boolean
      create_release:
        description: 'Create new release version (TBD)'
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout mhus-commons
        run: git clone https://github.com/mhus/mhus-commons.git
      - name: Build mhus-commons
        run: cd mhus-commons && mvn clean install -B -U
      - name: Cleanup mhus-commons
        run: rm -rf mhus-commons
      - name: Prepare
        run: ./kt2l-desktop/launcher/prepare.sh
      - name: Build maven linux-amd64
        run: mvn clean install -B -Plinux-amd64 -Pdeploy -Pproduction -Dspring.profiles.active=prod
      - name: Build maven macosx-aarch64
        if:  ${{ inputs.create_macosx_aarch64 }}
        run: cd kt2l-desktop;mvn install -B -Pmacosx-aarch64 -Pdeploy -Pproduction -Dspring.profiles.active=prod
      - name: Build maven macosx-x86_64
        if: ${{ inputs.create_all_others }}
        run: cd kt2l-desktop;mvn install -B -Pmacosx-x86_64 -Pdeploy -Pproduction -Dspring.profiles.active=prod
      - name: Build maven windows-amd64
        if:  ${{ inputs.create_windows_amd64 }}
        run: cd kt2l-desktop;mvn install -B -Pwindows-amd64 -Pdeploy -Pproduction -Dspring.profiles.active=prod
      - name: Integration Tests
        if:  ${{ inputs.integration_tests }}
        run: mvn -B verify -Pdeploy -Pproduction -Pintegration_tests -Dspring.profiles.active=prod
        env:
          TEST_DEBUG: false
          TEST_SCREENSHOTS: true
      - name: Copy Screenshots to cache
        if:  ${{ inputs.integration_tests }}
        run: |
          cd kt2l-test/target/screenshots
          for f in ls *.png; do 
            echo "Copy $f to cache"
            aws s3 cp $f s3://kt2l-downloads/cache/screenshots/$f; 
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Analyse
        if: ${{ inputs.sonarcloud }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mhus_kt2l -Plinux-amd64 -Pdeploy -Pproduction -Dspring.profiles.active=prod
      - name: Commit maybe changes to git
        run: |
          git config --global user.name 'Robot'
          git config --global user.email 'mhus@users.noreply.github.com'
          git commit -am "Build ${{ github.run_id }}" || true
          git push || true
      - name: Build Server ZIP
        run: ./kt2l-server/launcher/create-zip.sh
      - name: Build Server Container
        if: ${{ inputs.create_container }}
        run: ./kt2l-server/launcher/create-container.sh
      - name: Deploy Server ZIP
        if: ${{ inputs.create_server_zip }}
        run: ./kt2l-server/launcher/deploy-zip.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Deploy Desktop Jars
        run: ./kt2l-desktop/launcher/deploy-jars.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Deploy Server Container
        run: ./kt2l-server/launcher/deploy-container.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

  deb-amd64:
    if:  ${{ inputs.create_deb_amd64 }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Download Binaries
        run: |
          echo "Download kt2l-desktop.jar from cache"
          mkdir -p kt2l-desktop/target
          cd kt2l-desktop/target
          aws s3 cp s3://kt2l-downloads/cache/kt2l-desktop-linux-amd64.jar kt2l-desktop-linux-amd64.jar --quiet || exit 1
          aws s3 cp s3://kt2l-downloads/cache/kt2l-desktop-linux-amd64.txt kt2l-desktop-linux-amd64.txt --quiet || exit 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Create Desktop Bundle
        run: ./kt2l-desktop/launcher/create-deb-amd64.sh
      - name: Deploy Desktop Bundle
        run: ./kt2l-desktop/launcher/deploy-deb-amd64.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
  macosx-aarch64:
    needs: build
    if:  ${{ inputs.create_macosx_aarch64 }}
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Download Binaries
        run: |
          echo "Download kt2l-desktop.jar from cache"
          mkdir -p kt2l-desktop/target
          cd kt2l-desktop/target
          aws s3 cp s3://kt2l-downloads/cache/kt2l-desktop-macosx-aarch64.jar kt2l-desktop-macosx-aarch64.jar --quiet || exit 1
          aws s3 cp s3://kt2l-downloads/cache/kt2l-desktop-macosx-aarch64.txt kt2l-desktop-macosx-aarch64.txt --quiet || exit 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Create Desktop Bundle
        run: ./kt2l-desktop/launcher/create-macosx-aarch64.sh
      - name: Deploy Desktop Bundle
        run: ./kt2l-desktop/launcher/deploy-macosx-aarch64.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

  windows-amd64:
    if:  ${{ inputs.create_windows_amd64 }}
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Download Binaries
        shell: bash
        run: |
          echo "Download Binaries from cache"
          mkdir -p kt2l-desktop/target
          cd kt2l-desktop/target
          aws s3 cp s3://kt2l-downloads/cache/kt2l-desktop-windows-amd64.jar kt2l-desktop-windows-amd64.jar --quiet || exit 1
          aws s3 cp s3://kt2l-downloads/cache/kt2l-desktop-windows-amd64.txt kt2l-desktop-windows-amd64.txt --quiet || exit 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: create Windows desktop bundle
        shell: cmd
        run: kt2l-desktop/launcher/create-windows-amd64.bat
      - name: Deploy Windows desktop bundle
        shell: bash
        run: ./kt2l-desktop/launcher/deploy-windows-amd64.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

  documentation:
    if:  ${{ inputs.create_documentation }}
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: deploy_page
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      #      - name: Generate Javadoc
      #        run: mvn javadoc:aggregate -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: cd docs && npm ci
      - run: cd docs && npm run build
      #      - run: cp -R target/site/apidocs docs/build/
      - name: Setup gh-pages
        run: git clone https://github.com/mhus/kt2l.git -b gh-pages gh-pages
      - name: Copy content
        run: cd gh-pages/docs; rm -rf docs;cp -r ../../docs/build docs
      - name: prepare git config
        run: |
          cd gh-pages
          pwd
          echo "[gc]" >> .git/config
          echo "	auto = 0" >> .git/config
          echo "[http \"https://github.com/\"]" >> .git/config
          cat ../.git/config|grep "extraheader" >> .git/config
      - run: date > gh-pages/docs/docs/lastupdate.txt
      - name: commit
        run: |
          set -x
          cd gh-pages
          git add docs/docs
          git config --global user.name 'Robot'
          git config --global user.email 'mhus@users.noreply.github.com'
          git commit -m "Update docs"
          git push

  website:
    if:  ${{ inputs.update_website }}
    needs: [macosx-aarch64, windows-amd64, deb-amd64, documentation]
    runs-on: ubuntu-latest
    steps:
      - run: |
         curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $WORKFLOW_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/mhus/kt2l/actions/workflows/website.yml/dispatches \
            -d '{"ref":"gh-pages"}'
        env:
            WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}