
#
# This file is part of kt2l.
#
# kt2l is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# kt2l is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kt2l.  If not, see <http://www.gnu.org/licenses/>.
#

name: Release snapshot

on:
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: deploy_page
      cancel-in-progress: false
    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'

#      - name: Checkout mhus-commons
#        run: git clone https://github.com/mhus/mhus-commons.git
#      - name: Build mhus-commons
#        run: cd mhus-commons && mvn clean install -B -U
#      - name: Cleanup mhus-commons
#        run: rm -rf mhus-commons
      - name: Prepare
        run: ./kt2l-desktop/launcher/prepare.sh
      - name: Build maven
        run: mvn clean install -B -Pdeploy -Pproduction -Dspring.profiles.active=prod
      - name: Commit maybe changes to git
        run: |
          git config --global user.name 'Robot'
          git config --global user.email 'mhus@users.noreply.github.com'
          git commit -am "Build ${{ github.run_id }}"
          git push
      - name: Build Server ZIP
        run: ./kt2l-server/launcher/create-zip.sh
      - name: Build Server Container
        run: ./kt2l-server/launcher/create-container.sh
      - name: Deploy Server ZIP
        run: ./kt2l-server/launcher/deploy-zip.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Deploy Server Container
        run: ./kt2l-server/launcher/deploy-container.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

