name: Website

on:
  push:
    branches:
      - gh-pages
    paths:
      - 'kt2l.org/**'
  workflow_dispatch:
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: deploy_page
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Import download templates
        run: |
          ENTRIES=$(aws s3 ls kt2l-downloads/cache/downloads/ --no-paginate|cut -b 32-|grep -e ^download-)
          echo Found $ENTRIES
          for e in $(echo $ENTRIES); do
            echo "Copy $e"
            aws s3 cp "s3://kt2l-downloads/cache/downloads/$e" "kt2l.org/src/downloads/$e" --quiet || exit 1
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.2'
      - run: cd kt2l.org;npm ci
      - run: cd kt2l.org;npm run build
#      - run: npm test
      - run: rm -rf docs/static
      - run: cp -r kt2l.org/build/* docs/
      - run: date > docs/lastupdate.txt
      - name: commit snapshot
        if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
        run: |
          git add .
          git config --global user.name 'Robot'
          git config --global user.email 'mhus@users.noreply.github.com'
          git commit -am "Webpage"
          git push